//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyCacheHarness.ProxyRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyRef.IProxyService")]
    public interface IProxyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetJcdecauxContractsGeneric", ReplyAction="http://tempuri.org/IProxyService/GetJcdecauxContractsGenericResponse")]
        string GetJcdecauxContractsGeneric(int ttlSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetJcdecauxContractsGeneric", ReplyAction="http://tempuri.org/IProxyService/GetJcdecauxContractsGenericResponse")]
        System.Threading.Tasks.Task<string> GetJcdecauxContractsGenericAsync(int ttlSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetJcdecauxStationsGeneric", ReplyAction="http://tempuri.org/IProxyService/GetJcdecauxStationsGenericResponse")]
        string GetJcdecauxStationsGeneric(string contract, int ttlSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetJcdecauxStationsGeneric", ReplyAction="http://tempuri.org/IProxyService/GetJcdecauxStationsGenericResponse")]
        System.Threading.Tasks.Task<string> GetJcdecauxStationsGenericAsync(string contract, int ttlSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/Get", ReplyAction="http://tempuri.org/IProxyService/GetResponse")]
        string Get(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/Get", ReplyAction="http://tempuri.org/IProxyService/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetWithTtl", ReplyAction="http://tempuri.org/IProxyService/GetWithTtlResponse")]
        string GetWithTtl(string url, double ttlSeconds, bool forceRefresh, bool extendTtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetWithTtl", ReplyAction="http://tempuri.org/IProxyService/GetWithTtlResponse")]
        System.Threading.Tasks.Task<string> GetWithTtlAsync(string url, double ttlSeconds, bool forceRefresh, bool extendTtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/Evict", ReplyAction="http://tempuri.org/IProxyService/EvictResponse")]
        void Evict(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/Evict", ReplyAction="http://tempuri.org/IProxyService/EvictResponse")]
        System.Threading.Tasks.Task EvictAsync(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyServiceChannel : ProxyCacheHarness.ProxyRef.IProxyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyServiceClient : System.ServiceModel.ClientBase<ProxyCacheHarness.ProxyRef.IProxyService>, ProxyCacheHarness.ProxyRef.IProxyService {
        
        public ProxyServiceClient() {
        }
        
        public ProxyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetJcdecauxContractsGeneric(int ttlSeconds) {
            return base.Channel.GetJcdecauxContractsGeneric(ttlSeconds);
        }
        
        public System.Threading.Tasks.Task<string> GetJcdecauxContractsGenericAsync(int ttlSeconds) {
            return base.Channel.GetJcdecauxContractsGenericAsync(ttlSeconds);
        }
        
        public string GetJcdecauxStationsGeneric(string contract, int ttlSeconds) {
            return base.Channel.GetJcdecauxStationsGeneric(contract, ttlSeconds);
        }
        
        public System.Threading.Tasks.Task<string> GetJcdecauxStationsGenericAsync(string contract, int ttlSeconds) {
            return base.Channel.GetJcdecauxStationsGenericAsync(contract, ttlSeconds);
        }
        
        public string Get(string url) {
            return base.Channel.Get(url);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string url) {
            return base.Channel.GetAsync(url);
        }
        
        public string GetWithTtl(string url, double ttlSeconds, bool forceRefresh, bool extendTtl) {
            return base.Channel.GetWithTtl(url, ttlSeconds, forceRefresh, extendTtl);
        }
        
        public System.Threading.Tasks.Task<string> GetWithTtlAsync(string url, double ttlSeconds, bool forceRefresh, bool extendTtl) {
            return base.Channel.GetWithTtlAsync(url, ttlSeconds, forceRefresh, extendTtl);
        }
        
        public void Evict(string url) {
            base.Channel.Evict(url);
        }
        
        public System.Threading.Tasks.Task EvictAsync(string url) {
            return base.Channel.EvictAsync(url);
        }
    }
}
